# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keyboard Nest
email: call911@pm.me
description: Tips and tricks for keyboard-driven Linux navigation, operations, cross-program integrations etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chris-bz.github.io" # the base hostname & protocol for your site
github_username:  chris-bz

# Build settings
markdown: kramdown
theme: architect-jekyll-theme
